name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
        run: npm run build

      - name: Setup Git user
        run: |
          git config --global user.email "vandal12313@gmail.com" 
          git config --global user.name "Pug10rd"

      - name: Deploy
        run: |
          echo "machine github.com login ${{ secrets.GH_TOK }}" > ~/.netrc
          npm run deploy
